"""Build the one-file Windows .exe with Tesseract OCR bundled (so users install nothing).

Needs: python -m pip install pyinstaller, and Tesseract installed here (winget install UB-Mannheim.TesseractOCR).
Run from the project folder:  python tools/build_exe.py   ->  dist/Neocron Tech Counter.exe
"""
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TESS = Path(r"C:\Program Files\Tesseract-OCR")
STAGE = ROOT / "build" / "tesseract"


def strip_debug(path):
    """Drop the DWARF debug sections (names like "/19") and the symbol table from a MinGW DLL/EXE: libtesseract is
    101 MB with them and about 12 MB without. They are the last sections and the symbol table is at the end of
    the file, so this is just a truncation plus header fixes."""
    import struct
    import pefile
    pe = pefile.PE(str(path))
    secs = pe.sections
    keep = [s for s in secs if not s.Name.startswith(b"/")]
    if len(keep) == len(secs) or secs[:len(keep)] != keep:
        pe.close()
        return                                          # nothing to strip, or an unexpected layout: leave it alone
    data = bytearray(Path(path).read_bytes())
    pe_off = pe.DOS_HEADER.e_lfanew
    opt_size = pe.FILE_HEADER.SizeOfOptionalHeader
    table = pe_off + 24 + opt_size
    last = keep[-1]
    align = pe.OPTIONAL_HEADER.SectionAlignment
    image = (last.VirtualAddress + max(last.Misc_VirtualSize, 1) + align - 1) // align * align
    end = last.PointerToRawData + last.SizeOfRawData
    struct.pack_into("<H", data, pe_off + 6, len(keep))                     # NumberOfSections
    struct.pack_into("<II", data, pe_off + 12, 0, 0)                        # PointerToSymbolTable, NumberOfSymbols
    struct.pack_into("<I", data, pe_off + 24 + 56, image)                   # SizeOfImage (PE32+: offset 56)
    struct.pack_into("<I", data, pe_off + 24 + 64, 0)                       # CheckSum
    data[table + 40 * len(keep): table + 40 * len(secs)] = bytes(40 * (len(secs) - len(keep)))
    pe.close()
    Path(path).write_bytes(bytes(data[:end]))


def needed_dlls():
    """The DLLs tesseract.exe really loads (its import closure): about half of the install. The rest (cairo, pango,
    ICU...) is only for the training and PDF tools."""
    import pefile
    have = {p.name.lower(): p for p in TESS.glob("*.dll")}
    need, todo = set(), [TESS / "tesseract.exe"]
    while todo:
        pe = pefile.PE(str(todo.pop()), fast_load=True)
        pe.parse_data_directories([pefile.DIRECTORY_ENTRY["IMAGE_DIRECTORY_ENTRY_IMPORT"]])
        for entry in getattr(pe, "DIRECTORY_ENTRY_IMPORT", []):
            name = entry.dll.decode().lower()
            if name in have and name not in need:
                need.add(name)
                todo.append(have[name])
        pe.close()
    return [have[n] for n in sorted(need)]


def stage_tesseract():
    """Only what scanning needs: tesseract.exe, its DLLs and the English model."""
    shutil.rmtree(STAGE, ignore_errors=True)
    (STAGE / "tessdata").mkdir(parents=True)
    for f in [TESS / "tesseract.exe", *needed_dlls()]:
        shutil.copy2(f, STAGE / f.name)
        strip_debug(STAGE / f.name)
    shutil.copy2(TESS / "tessdata" / "eng.traineddata", STAGE / "tessdata" / "eng.traineddata")
    licence = next(TESS.glob("doc/LICENSE*"), None)
    if licence:
        shutil.copy2(licence, STAGE / "LICENSE-tesseract.txt")


SPEC = """# generated by tools/build_exe.py
a = Analysis([{entry!r}], pathex=[], binaries=[], datas={datas!r}, hiddenimports=[], hookspath=[],
             excludes=["unittest", "pydoc", "doctest", "pytest", "matplotlib", "scipy", "pandas"])
# OpenCV's video codec library (about 30 MB) is never used: this app only reads still screenshots
a.binaries = [b for b in a.binaries if "opencv_videoio_ffmpeg" not in b[0]]
pyz = PYZ(a.pure)
exe = EXE(pyz, a.scripts, a.binaries, a.datas, [], name="Neocron Tech Counter", console=False, icon={icon!r},
          upx=False, runtime_tmpdir=None)
"""


def main():
    stage_tesseract()
    datas = [(str(ROOT / "assets"), "assets"), (str(ROOT / "data" / "tech_sets.json"), "data"),
             (str(STAGE), "tesseract")]
    spec = ROOT / "build" / "ntc.spec"
    spec.write_text(SPEC.format(entry=str(ROOT / "run_ntc.py"), datas=datas, icon=str(ROOT / "assets" / "icon.ico")),
                    encoding="utf-8")
    subprocess.run([sys.executable, "-m", "PyInstaller", "--noconfirm", "--distpath", str(ROOT / "dist"),
                    "--workpath", str(ROOT / "build" / "work"), str(spec)], check=True, cwd=ROOT)


if __name__ == "__main__":
    main()
